openconfig-network-instance:network-instances:
  network-instance:
  - name: default
    config:
      name: default
      type: DEFAULT_INSTANCE
      enabled: true
    protocols:
      protocol:
      - identifier: openconfig-policy-types:BGP
        name: BGP
        config:
          identifier: openconfig-policy-types:BGP
          name: BGP
        bgp:
          global:
            config:
              as: 65000
              router-id: 10.0.1.1
          neighbors:
            neighbor:
            - neighbor-address: 10.0.0.1  # Access switch 1
              config:
                neighbor-address: 10.0.0.1
                peer-as: 65000
                route-reflector-client: true
              afi-safis:
                afi-safi:
                - afi-safi-name: openconfig-bgp-types:L2VPN_EVPN
                  config:
                    afi-safi-name: openconfig-bgp-types:L2VPN_EVPN
                    enabled: true
            - neighbor-address: 10.0.0.2  # Access switch 2
              config:
                neighbor-address: 10.0.0.2
                peer-as: 65000
                route-reflector-client: true
              afi-safis:
                afi-safi:
                - afi-safi-name: openconfig-bgp-types:L2VPN_EVPN
                  config:
                    afi-safi-name: openconfig-bgp-types:L2VPN_EVPN
                    enabled: true