
- name: "ethernet-1/3"
  admin-state: enable
  vlan-tagging: false
  subinterface:
   - index: 0
     type: bridged
     admin-state: enable
     vlan:
      encap:
       single-tagged:
        vlan-id: 10

- name: "ethernet-1/1"
  admin-state: enable
  vlan-tagging: true
  subinterface:
   - index: 0
     type: bridged
     admin-state: enable
     vlan:
      encap:
       single-tagged:
        vlan-id: 10

- name: "ethernet-1/2"
  admin-state: enable
  vlan-tagging: true
  subinterface:
   - index: 0
     type: bridged
     admin-state: enable
     vlan:
      encap:
       single-tagged:
        vlan-id: 10
